export const skillList = [
  "Java",
  "Spring Boot",
  "Spring Security",
  "Spring Data JPA",
  "Hibernate",
  "Maven",
  "Spring Batch",
  "JDBC",
  "JPA",
  "OAuth 2.0",
  "JWT",
  "REST",
  "SOAP",
  "OData",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Oracle DB",
  "IBM Db2",
  "Redis",
  "Apache CMIS",
  "Azure Blob Storage",
  "Kafka",
  "Docker",
  "Kubernetes",
  "Rancher",
  "GitHub",
  "GitLab",
  "Git",
  "React",
  "JavaScript",
  "TypeScript",
  "Jest",
  "Spring Cloud (Eureka)",
  "Microfrontend Architecture",
  "Microservices",
  "High-Concurrency Systems",
  "API Design",
  "Secure Architecture",
  "Scalable Backend Development",
  "Software Architecture",
  "Dynatrace",
  "ELK Stack",
  "Splunk",
  "XML Dashboards",
  "Alerting",
  "GoCD",
  "Trunk-Based Development",
  "Continuous Delivery",
  "SDLC",
  "Monitoring & Observability",
  "Multithreading",
  "Incident Response",
  "Clean Code",
  "Legacy Modernization",
  "Product Transformation",
  "High-Frequency Systems",
  "Team Leadership",
  "SDLC Best Practices",
];
